
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServerEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ServerEvent
 * 
 */
export type ServerEventModel = runtime.Types.Result.DefaultSelection<Prisma.$ServerEventPayload>

export type AggregateServerEvent = {
  _count: ServerEventCountAggregateOutputType | null
  _min: ServerEventMinAggregateOutputType | null
  _max: ServerEventMaxAggregateOutputType | null
}

export type ServerEventMinAggregateOutputType = {
  id: string | null
  type: $Enums.ServerEventType | null
  message: string | null
  created: Date | null
  updated: Date | null
}

export type ServerEventMaxAggregateOutputType = {
  id: string | null
  type: $Enums.ServerEventType | null
  message: string | null
  created: Date | null
  updated: Date | null
}

export type ServerEventCountAggregateOutputType = {
  id: number
  type: number
  message: number
  created: number
  updated: number
  _all: number
}


export type ServerEventMinAggregateInputType = {
  id?: true
  type?: true
  message?: true
  created?: true
  updated?: true
}

export type ServerEventMaxAggregateInputType = {
  id?: true
  type?: true
  message?: true
  created?: true
  updated?: true
}

export type ServerEventCountAggregateInputType = {
  id?: true
  type?: true
  message?: true
  created?: true
  updated?: true
  _all?: true
}

export type ServerEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServerEvent to aggregate.
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerEvents to fetch.
   */
  orderBy?: Prisma.ServerEventOrderByWithRelationInput | Prisma.ServerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServerEvents
  **/
  _count?: true | ServerEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServerEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServerEventMaxAggregateInputType
}

export type GetServerEventAggregateType<T extends ServerEventAggregateArgs> = {
      [P in keyof T & keyof AggregateServerEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServerEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateServerEvent[P]>
}




export type ServerEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServerEventWhereInput
  orderBy?: Prisma.ServerEventOrderByWithAggregationInput | Prisma.ServerEventOrderByWithAggregationInput[]
  by: Prisma.ServerEventScalarFieldEnum[] | Prisma.ServerEventScalarFieldEnum
  having?: Prisma.ServerEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServerEventCountAggregateInputType | true
  _min?: ServerEventMinAggregateInputType
  _max?: ServerEventMaxAggregateInputType
}

export type ServerEventGroupByOutputType = {
  id: string
  type: $Enums.ServerEventType
  message: string
  created: Date
  updated: Date
  _count: ServerEventCountAggregateOutputType | null
  _min: ServerEventMinAggregateOutputType | null
  _max: ServerEventMaxAggregateOutputType | null
}

type GetServerEventGroupByPayload<T extends ServerEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServerEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServerEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServerEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServerEventGroupByOutputType[P]>
      }
    >
  >



export type ServerEventWhereInput = {
  AND?: Prisma.ServerEventWhereInput | Prisma.ServerEventWhereInput[]
  OR?: Prisma.ServerEventWhereInput[]
  NOT?: Prisma.ServerEventWhereInput | Prisma.ServerEventWhereInput[]
  id?: Prisma.StringFilter<"ServerEvent"> | string
  type?: Prisma.EnumServerEventTypeFilter<"ServerEvent"> | $Enums.ServerEventType
  message?: Prisma.StringFilter<"ServerEvent"> | string
  created?: Prisma.DateTimeFilter<"ServerEvent"> | Date | string
  updated?: Prisma.DateTimeFilter<"ServerEvent"> | Date | string
}

export type ServerEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type ServerEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ServerEventWhereInput | Prisma.ServerEventWhereInput[]
  OR?: Prisma.ServerEventWhereInput[]
  NOT?: Prisma.ServerEventWhereInput | Prisma.ServerEventWhereInput[]
  type?: Prisma.EnumServerEventTypeFilter<"ServerEvent"> | $Enums.ServerEventType
  message?: Prisma.StringFilter<"ServerEvent"> | string
  created?: Prisma.DateTimeFilter<"ServerEvent"> | Date | string
  updated?: Prisma.DateTimeFilter<"ServerEvent"> | Date | string
}, "id">

export type ServerEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  _count?: Prisma.ServerEventCountOrderByAggregateInput
  _max?: Prisma.ServerEventMaxOrderByAggregateInput
  _min?: Prisma.ServerEventMinOrderByAggregateInput
}

export type ServerEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServerEventScalarWhereWithAggregatesInput | Prisma.ServerEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServerEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServerEventScalarWhereWithAggregatesInput | Prisma.ServerEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServerEvent"> | string
  type?: Prisma.EnumServerEventTypeWithAggregatesFilter<"ServerEvent"> | $Enums.ServerEventType
  message?: Prisma.StringWithAggregatesFilter<"ServerEvent"> | string
  created?: Prisma.DateTimeWithAggregatesFilter<"ServerEvent"> | Date | string
  updated?: Prisma.DateTimeWithAggregatesFilter<"ServerEvent"> | Date | string
}

export type ServerEventCreateInput = {
  id?: string
  type?: $Enums.ServerEventType
  message: string
  created?: Date | string
  updated?: Date | string
}

export type ServerEventUncheckedCreateInput = {
  id?: string
  type?: $Enums.ServerEventType
  message: string
  created?: Date | string
  updated?: Date | string
}

export type ServerEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumServerEventTypeFieldUpdateOperationsInput | $Enums.ServerEventType
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServerEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumServerEventTypeFieldUpdateOperationsInput | $Enums.ServerEventType
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServerEventCreateManyInput = {
  id?: string
  type?: $Enums.ServerEventType
  message: string
  created?: Date | string
  updated?: Date | string
}

export type ServerEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumServerEventTypeFieldUpdateOperationsInput | $Enums.ServerEventType
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServerEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumServerEventTypeFieldUpdateOperationsInput | $Enums.ServerEventType
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServerEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type ServerEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type ServerEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type EnumServerEventTypeFieldUpdateOperationsInput = {
  set?: $Enums.ServerEventType
}



export type ServerEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  message?: boolean
  created?: boolean
  updated?: boolean
}, ExtArgs["result"]["serverEvent"]>

export type ServerEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  message?: boolean
  created?: boolean
  updated?: boolean
}, ExtArgs["result"]["serverEvent"]>

export type ServerEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  message?: boolean
  created?: boolean
  updated?: boolean
}, ExtArgs["result"]["serverEvent"]>

export type ServerEventSelectScalar = {
  id?: boolean
  type?: boolean
  message?: boolean
  created?: boolean
  updated?: boolean
}

export type ServerEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "message" | "created" | "updated", ExtArgs["result"]["serverEvent"]>

export type $ServerEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServerEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.ServerEventType
    message: string
    created: Date
    updated: Date
  }, ExtArgs["result"]["serverEvent"]>
  composites: {}
}

export type ServerEventGetPayload<S extends boolean | null | undefined | ServerEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServerEventPayload, S>

export type ServerEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServerEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServerEventCountAggregateInputType | true
  }

export interface ServerEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServerEvent'], meta: { name: 'ServerEvent' } }
  /**
   * Find zero or one ServerEvent that matches the filter.
   * @param {ServerEventFindUniqueArgs} args - Arguments to find a ServerEvent
   * @example
   * // Get one ServerEvent
   * const serverEvent = await prisma.serverEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServerEventFindUniqueArgs>(args: Prisma.SelectSubset<T, ServerEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServerEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServerEventFindUniqueOrThrowArgs} args - Arguments to find a ServerEvent
   * @example
   * // Get one ServerEvent
   * const serverEvent = await prisma.serverEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServerEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServerEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServerEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventFindFirstArgs} args - Arguments to find a ServerEvent
   * @example
   * // Get one ServerEvent
   * const serverEvent = await prisma.serverEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServerEventFindFirstArgs>(args?: Prisma.SelectSubset<T, ServerEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServerEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventFindFirstOrThrowArgs} args - Arguments to find a ServerEvent
   * @example
   * // Get one ServerEvent
   * const serverEvent = await prisma.serverEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServerEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServerEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServerEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServerEvents
   * const serverEvents = await prisma.serverEvent.findMany()
   * 
   * // Get first 10 ServerEvents
   * const serverEvents = await prisma.serverEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serverEventWithIdOnly = await prisma.serverEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServerEventFindManyArgs>(args?: Prisma.SelectSubset<T, ServerEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServerEvent.
   * @param {ServerEventCreateArgs} args - Arguments to create a ServerEvent.
   * @example
   * // Create one ServerEvent
   * const ServerEvent = await prisma.serverEvent.create({
   *   data: {
   *     // ... data to create a ServerEvent
   *   }
   * })
   * 
   */
  create<T extends ServerEventCreateArgs>(args: Prisma.SelectSubset<T, ServerEventCreateArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServerEvents.
   * @param {ServerEventCreateManyArgs} args - Arguments to create many ServerEvents.
   * @example
   * // Create many ServerEvents
   * const serverEvent = await prisma.serverEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServerEventCreateManyArgs>(args?: Prisma.SelectSubset<T, ServerEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServerEvents and returns the data saved in the database.
   * @param {ServerEventCreateManyAndReturnArgs} args - Arguments to create many ServerEvents.
   * @example
   * // Create many ServerEvents
   * const serverEvent = await prisma.serverEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServerEvents and only return the `id`
   * const serverEventWithIdOnly = await prisma.serverEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServerEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServerEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServerEvent.
   * @param {ServerEventDeleteArgs} args - Arguments to delete one ServerEvent.
   * @example
   * // Delete one ServerEvent
   * const ServerEvent = await prisma.serverEvent.delete({
   *   where: {
   *     // ... filter to delete one ServerEvent
   *   }
   * })
   * 
   */
  delete<T extends ServerEventDeleteArgs>(args: Prisma.SelectSubset<T, ServerEventDeleteArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServerEvent.
   * @param {ServerEventUpdateArgs} args - Arguments to update one ServerEvent.
   * @example
   * // Update one ServerEvent
   * const serverEvent = await prisma.serverEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServerEventUpdateArgs>(args: Prisma.SelectSubset<T, ServerEventUpdateArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServerEvents.
   * @param {ServerEventDeleteManyArgs} args - Arguments to filter ServerEvents to delete.
   * @example
   * // Delete a few ServerEvents
   * const { count } = await prisma.serverEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServerEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServerEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServerEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServerEvents
   * const serverEvent = await prisma.serverEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServerEventUpdateManyArgs>(args: Prisma.SelectSubset<T, ServerEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServerEvents and returns the data updated in the database.
   * @param {ServerEventUpdateManyAndReturnArgs} args - Arguments to update many ServerEvents.
   * @example
   * // Update many ServerEvents
   * const serverEvent = await prisma.serverEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServerEvents and only return the `id`
   * const serverEventWithIdOnly = await prisma.serverEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServerEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServerEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServerEvent.
   * @param {ServerEventUpsertArgs} args - Arguments to update or create a ServerEvent.
   * @example
   * // Update or create a ServerEvent
   * const serverEvent = await prisma.serverEvent.upsert({
   *   create: {
   *     // ... data to create a ServerEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServerEvent we want to update
   *   }
   * })
   */
  upsert<T extends ServerEventUpsertArgs>(args: Prisma.SelectSubset<T, ServerEventUpsertArgs<ExtArgs>>): Prisma.Prisma__ServerEventClient<runtime.Types.Result.GetResult<Prisma.$ServerEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServerEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventCountArgs} args - Arguments to filter ServerEvents to count.
   * @example
   * // Count the number of ServerEvents
   * const count = await prisma.serverEvent.count({
   *   where: {
   *     // ... the filter for the ServerEvents we want to count
   *   }
   * })
  **/
  count<T extends ServerEventCountArgs>(
    args?: Prisma.Subset<T, ServerEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServerEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServerEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServerEventAggregateArgs>(args: Prisma.Subset<T, ServerEventAggregateArgs>): Prisma.PrismaPromise<GetServerEventAggregateType<T>>

  /**
   * Group by ServerEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServerEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServerEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServerEventGroupByArgs['orderBy'] }
      : { orderBy?: ServerEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServerEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServerEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServerEvent model
 */
readonly fields: ServerEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServerEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServerEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServerEvent model
 */
export interface ServerEventFieldRefs {
  readonly id: Prisma.FieldRef<"ServerEvent", 'String'>
  readonly type: Prisma.FieldRef<"ServerEvent", 'ServerEventType'>
  readonly message: Prisma.FieldRef<"ServerEvent", 'String'>
  readonly created: Prisma.FieldRef<"ServerEvent", 'DateTime'>
  readonly updated: Prisma.FieldRef<"ServerEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServerEvent findUnique
 */
export type ServerEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * Filter, which ServerEvent to fetch.
   */
  where: Prisma.ServerEventWhereUniqueInput
}

/**
 * ServerEvent findUniqueOrThrow
 */
export type ServerEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * Filter, which ServerEvent to fetch.
   */
  where: Prisma.ServerEventWhereUniqueInput
}

/**
 * ServerEvent findFirst
 */
export type ServerEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * Filter, which ServerEvent to fetch.
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerEvents to fetch.
   */
  orderBy?: Prisma.ServerEventOrderByWithRelationInput | Prisma.ServerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServerEvents.
   */
  cursor?: Prisma.ServerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServerEvents.
   */
  distinct?: Prisma.ServerEventScalarFieldEnum | Prisma.ServerEventScalarFieldEnum[]
}

/**
 * ServerEvent findFirstOrThrow
 */
export type ServerEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * Filter, which ServerEvent to fetch.
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerEvents to fetch.
   */
  orderBy?: Prisma.ServerEventOrderByWithRelationInput | Prisma.ServerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServerEvents.
   */
  cursor?: Prisma.ServerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServerEvents.
   */
  distinct?: Prisma.ServerEventScalarFieldEnum | Prisma.ServerEventScalarFieldEnum[]
}

/**
 * ServerEvent findMany
 */
export type ServerEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * Filter, which ServerEvents to fetch.
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServerEvents to fetch.
   */
  orderBy?: Prisma.ServerEventOrderByWithRelationInput | Prisma.ServerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServerEvents.
   */
  cursor?: Prisma.ServerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServerEvents.
   */
  skip?: number
  distinct?: Prisma.ServerEventScalarFieldEnum | Prisma.ServerEventScalarFieldEnum[]
}

/**
 * ServerEvent create
 */
export type ServerEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * The data needed to create a ServerEvent.
   */
  data: Prisma.XOR<Prisma.ServerEventCreateInput, Prisma.ServerEventUncheckedCreateInput>
}

/**
 * ServerEvent createMany
 */
export type ServerEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServerEvents.
   */
  data: Prisma.ServerEventCreateManyInput | Prisma.ServerEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServerEvent createManyAndReturn
 */
export type ServerEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * The data used to create many ServerEvents.
   */
  data: Prisma.ServerEventCreateManyInput | Prisma.ServerEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServerEvent update
 */
export type ServerEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * The data needed to update a ServerEvent.
   */
  data: Prisma.XOR<Prisma.ServerEventUpdateInput, Prisma.ServerEventUncheckedUpdateInput>
  /**
   * Choose, which ServerEvent to update.
   */
  where: Prisma.ServerEventWhereUniqueInput
}

/**
 * ServerEvent updateMany
 */
export type ServerEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServerEvents.
   */
  data: Prisma.XOR<Prisma.ServerEventUpdateManyMutationInput, Prisma.ServerEventUncheckedUpdateManyInput>
  /**
   * Filter which ServerEvents to update
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * Limit how many ServerEvents to update.
   */
  limit?: number
}

/**
 * ServerEvent updateManyAndReturn
 */
export type ServerEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * The data used to update ServerEvents.
   */
  data: Prisma.XOR<Prisma.ServerEventUpdateManyMutationInput, Prisma.ServerEventUncheckedUpdateManyInput>
  /**
   * Filter which ServerEvents to update
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * Limit how many ServerEvents to update.
   */
  limit?: number
}

/**
 * ServerEvent upsert
 */
export type ServerEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * The filter to search for the ServerEvent to update in case it exists.
   */
  where: Prisma.ServerEventWhereUniqueInput
  /**
   * In case the ServerEvent found by the `where` argument doesn't exist, create a new ServerEvent with this data.
   */
  create: Prisma.XOR<Prisma.ServerEventCreateInput, Prisma.ServerEventUncheckedCreateInput>
  /**
   * In case the ServerEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServerEventUpdateInput, Prisma.ServerEventUncheckedUpdateInput>
}

/**
 * ServerEvent delete
 */
export type ServerEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
  /**
   * Filter which ServerEvent to delete.
   */
  where: Prisma.ServerEventWhereUniqueInput
}

/**
 * ServerEvent deleteMany
 */
export type ServerEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServerEvents to delete
   */
  where?: Prisma.ServerEventWhereInput
  /**
   * Limit how many ServerEvents to delete.
   */
  limit?: number
}

/**
 * ServerEvent without action
 */
export type ServerEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServerEvent
   */
  select?: Prisma.ServerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServerEvent
   */
  omit?: Prisma.ServerEventOmit<ExtArgs> | null
}
